CREATE DATABASE QLGV
--1.Tạo quan hệ và khai báo tất cả các ràng buộc khóa chính, khóa ngoại. Thêm vào 3 thuộc tính GHICHU, DIEMTB, XEPLOAI cho quan hệ HOCVIEN.
USE QLGV
CREATE TABLE KHOA(
    MAKHOA  varchar(4) primary key,
    TENKHOA	varchar(40),
    NGTLAP	smalldatetime,
    TRGKHOA	char(4),
)

CREATE TABLE GIAOVIEN(
    MAGV char(4) PRIMARY KEY,
    HOTEN   varchar(40),
    HOCVI VARCHAR(10),
    HOCHAM	varchar(10),
    GIOITINH	varchar(3),
    NGSINH smalldatetime, 
    NGVL	smalldatetime,
    HESO	numeric(4,2),
    MUCLUONG    money,
    MAKHOA	varchar(4),
    CONSTRAINT FK_GIAOVIEN FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
)

--Them rang buoc khoa ngoai cho cot TRGKHOA trong KHOA
ALTER TABLE KHOA ADD CONSTRAINT FK_KHOA_TRGKHOA FOREIGN KEY (TRGKHOA) REFERENCES GIAOVIEN(MAGV);

CREATE TABLE MONHOC(
    MAMH    varchar(10) PRIMARY KEY,
    TENMH	varchar(40),
    TCLT	tinyint,
    TCTH	tinyint,
    MAKHOA	varchar(4),
    CONSTRAINT FK_MONHOC FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
)

CREATE TABLE DIEUKIEN(
    MAMH    varchar(10),
    MAMH_TRUOC	varchar(10),
    CONSTRAINT PK_DIEUKIEN_MAMH PRIMARY KEY (MAMH, MAMH_TRUOC),
    CONSTRAINT FK_DIEUKIEN_MAMH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
    CONSTRAINT FK_DIEUKIEN_MAMH_TRUOC FOREIGN KEY (MAMH_TRUOC) REFERENCES MONHOC(MAMH)
)

CREATE TABLE LOP(
    MALOP   char(3) PRIMARY KEY,
    TENLOP  varchar(40),
    TRGLOP  char(5),
    SISO    tinyint,
    MAGVCN  char(4),
    CONSTRAINT FK_LOP_MAGVCN FOREIGN KEY (MAGVCN) REFERENCES GIAOVIEN(MAGV)
)

CREATE TABLE HOCVIEN(
    MAHV    char(5) PRIMARY KEY,
    HO  varchar(40),
    TEN varchar(10),
    NGSINH  smalldatetime,
    GIOITINH    varchar(3),
    NOISINH varchar(40),
    MALOP   char(3),
    CONSTRAINT FK_HOCVIEN_MALOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)
)

ALTER TABLE LOP ADD CONSTRAINT FK_LOP_TRGLOP FOREIGN KEY (TRGLOP) REFERENCES HOCVIEN(MAHV);

CREATE TABLE GIANGDAY(
    MALOP   char(3),
    MAMH	varchar(10),
    MAGV	char(4),
    HOCKY	tinyint,
    NAM smallint,
    TUNGAY  smalldatetime, 
    DENNGAY	smalldatetime,
    CONSTRAINT PK_GIANGDAY PRIMARY KEY (MALOP, MAMH),
    CONSTRAINT FK_GIANGDAY_MAGV FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV),
    CONSTRAINT FK_GIANGDAY_MALOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP),
    CONSTRAINT FK_GIANGDAY_MAMH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)
)

CREATE TABLE KETQUATHI(
    MAHV	char(5),
    MAMH	varchar(10),
    LANTHI	tinyint,
    NGTHI	smalldatetime,
    DIEM	numeric(4,2),
    KQUA	varchar(10),
    CONSTRAINT PK_KETQUATHI PRIMARY KEY (MAHV,MAMH,LANTHI),
    CONSTRAINT FK_KETQUATHI_MAHV FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV),
    CONSTRAINT FK_KETQUATHI_MAMH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)
)

--Add GHICHU, DIEMTB, XEPLOAI cho quan hệ HOCVIEN
ALTER TABLE HOCVIEN ADD GHICHU TEXT;
ALTER TABLE HOCVIEN ADD DIEMTB NUMERIC(3,2);
ALTER TABLE HOCVIEN ADD XEPLOAI VARCHAR(10);

