USE MASTER
IF EXISTS (SELECT * FROM SYS.DATABASES WHERE NAME = 'BAITHI')
BEGIN
	ALTER DATABASE BAITHI SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE BAITHI;
END
GO
CREATE DATABASE BAITHI

SET DATEFORMAT DMY

--Câu 1:
CREATE TABLE  KHACHHANG (MAKH VARCHAR(10) PRIMARY KEY, HOTEN NVARCHAR(30), NGSINH SMALLDATETIME, SDT VARCHAR(20), LOAIKH VARCHAR(10), KHUYENMAI INT)
CREATE TABLE  GOIDV (
MAGOI VARCHAR(10) PRIMARY KEY, 
TENGOI NVARCHAR(30), 
SKKTS INT, 
SKHD INT, 
GIACUOC MONEY
)

CREATE TABLE HOPDONG (
SOHD VARCHAR(10) PRIMARY KEY, 
MAKH VARCHAR(10) FOREIGN KEY REFERENCES KHACHHANG(MAKH), 
SOTV INT, 
NGLAP SMALLDATETIME
)

CREATE TABLE CTHD (
SOHD VARCHAR(10), 
MAGOI VARCHAR(10), 
NGDK SMALLDATETIME,
CONSTRAINT PK_CTHD PRIMARY KEY(SOHD, MAGOI),
CONSTRAINT FK_SOHD_CTHD FOREIGN KEY (SOHD) REFERENCES HOPDONG(SOHD),
CONSTRAINT FK_MAGOI_CTHD FOREIGN KEY (MAGOI) REFERENCES GOIDV(MAGOI),
)

--Câu 2:
SET DATEFORMAT DMY
INSERT INTO KHACHHANG VALUES('3328','Ly Hong Bao', '04/05/1999', '03788243xx', 'VIP', 5)
INSERT INTO KHACHHANG VALUES('4012','Truong Thi Hoai Anh', '08/11/1998', '03762061xx', 'Thuong', 0)
INSERT INTO KHACHHANG VALUES('1209','Do Huu Luong', '10/11/1999', '08691619xx', 'VIP', 5)

INSERT INTO GOIDV  VALUES('G001','Ngoai hang Anh', 30, 10, 199000)
INSERT INTO GOIDV  VALUES('G002','Kho phim bom tan', 15, 8, 99000)
INSERT INTO GOIDV  VALUES('G003','K-Pop world', 3, 3, 49000)

INSERT INTO HOPDONG  VALUES('8276','3328', 10, '09/10/2018')
INSERT INTO HOPDONG  VALUES('7523','1209', 1, '28/11/2018')
INSERT INTO HOPDONG  VALUES('2764','4012', 3, '15/07/2018')

INSERT INTO CTHD VALUES('2764','G001', '16/07/2018')
INSERT INTO CTHD VALUES('2764','G002', '23/10/2018')
INSERT INTO CTHD VALUES('8276','G001', '11/11/2018')

-- Câu 3:
ALTER TABLE KHACHHANG ADD CONSTRAINT CK_LOAIKH_KHUYENMAI
CHECK (
	LOAIKH = 'VIP' AND KHUYENMAI = 5
	OR LOAIKH != 'VIP'
)

--Câu 4:
-----------------------------------
--          | THEM    XOA   SUA
--CTHD      |  +       -    +(NGDK)
--HOPDONG   |  -      -(*)  +(NGLAP)

GO
CREATE TRIGGER TRG_THEM_CTHD ON CTHD
FOR INSERT
AS BEGIN
	DECLARE @NGDK SMALLDATETIME, @NGLAP SMALLDATETIME, @SOHD VARCHAR(10)
	SELECT @SOHD = SOHD, @NGDK = NGDK FROM inserted
	SELECT @NGLAP = NGLAP FROM HOPDONG WHERE @SOHD = SOHD
	IF (@NGDK >= @NGLAP) 
		PRINT N'Thêm thành công!'
	ELSE 
		BEGIN
			PRINT N'Ngày đăng ký gói dịch vụ phải lớn hơn hoặc bằng ngày lập hợp đồng'
			ROLLBACK TRAN
		END
END

GO
CREATE TRIGGER TRG_SUA_CTHD ON CTHD
FOR UPDATE
AS BEGIN
	DECLARE @NGDK SMALLDATETIME, @NGLAP SMALLDATETIME, @SOHD VARCHAR(10)
	SELECT @SOHD = SOHD, @NGDK = NGDK FROM inserted
	SELECT @NGLAP = NGLAP FROM HOPDONG WHERE @SOHD = SOHD
	IF (@NGDK >= @NGLAP) 
		PRINT N'Sửa thành công!'
	ELSE 
		BEGIN
			PRINT N'Ngày đăng ký gói dịch vụ phải lớn hơn hoặc bằng ngày lập hợp đồng'
			ROLLBACK TRAN
		END
END

GO
CREATE TRIGGER TRG_SUA_HOPDONG ON HOPDONG
FOR UPDATE
AS BEGIN
	DECLARE @NGLAP SMALLDATETIME, @SOHD VARCHAR(10)
	SELECT @SOHD = SOHD, @NGLAP = NGLAP FROM inserted
	IF (EXISTS (
		SELECT * FROM CTHD CT WHERE SOHD = @SOHD
		AND NGDK < @NGLAP
	)) 
		BEGIN
			PRINT N'Ngày đăng ký gói dịch vụ phải lớn hơn hoặc bằng ngày lập hợp đồng'
			ROLLBACK TRAN
		END
	ELSE 
		PRINT N'Sửa thành công!'

END

--Câu 5:
SELECT KH.MAKH, HOTEN FROM HOPDONG HD, KHACHHANG KH
WHERE MONTH(NGLAP) >= 10 
AND MONTH(NGLAP) <= 12 
AND YEAR(NGLAP) = 2018
AND KH.MAKH = HD.MAKH
ORDER BY NGSINH ASC

--Câu 6:
SELECT TOP 1 WITH TIES MAGOI
FROM CTHD 
WHERE YEAR(NGDK) = 2018
GROUP BY 
MAGOI
ORDER BY COUNT(MAGOI) DESC

--Câu 7:
SELECT MAGOI FROM CTHD 
EXCEPT 
SELECT MAGOI FROM CTHD CT2, KHACHHANG KH2, HOPDONG HD2
WHERE CT2.SOHD = HD2.SOHD
AND KH2.MAKH = HD2.MAKH
AND LOAIKH = 'VIP' OR LOAIKH = 'Thuong'

--Câu 8:
SELECT KH.MAKH, HOTEN FROM KHACHHANG KH
WHERE LOAIKH = 'Thuong'
AND NOT EXISTS(
	SELECT * FROM GOIDV DV 
	WHERE GIACUOC > 50000
	AND NOT EXISTS (
		SELECT * FROM HOPDONG HD, CTHD CT
		WHERE HD.MAKH = KH.MAKH
		AND HD.SOHD = CT.SOHD
		AND CT.MAGOI = DV.MAGOI
	)
)