-- Cau 1
CREATE DATABASE BAITHI
SET DATEFORMAT DMY
--1
CREATE TABLE KHACHTHUE(
MAKT CHAR(6) PRIMARY KEY,
TENKT VARCHAR(40),
NGSINH SMALLDATETIME,
CMND CHAR(9),
DIACHI VARCHAR(50),
)
CREATE TABLE XEMAY(
MAXE CHAR(5) PRIMARY KEY,
TENXE VARCHAR(30),
DUNGTICH INT,
GIA MONEY,
TINHTRANG VARCHAR (10)
)
CREATE TABLE E_BILL(
SOHD INT PRIMARY KEY,
NGTHUE SMALLDATETIME,
NGTRA SMALLDATETIME,
MAKT CHAR(6) FOREIGN KEY REFERENCES KHACHTHUE(MAKT)
)

CREATE TABLE CTTHUE(
SOHD INT  FOREIGN KEY REFERENCES E_BILL(SOHD),
MAXE CHAR(5) FOREIGN KEY REFERENCES XEMAY(MAXE),
SL INT,
CONSTRAINT PK_CTTHUE PRIMARY KEY (SOHD,MAXE)
)


--Cau 2
--2
--KHACHTHUE
INSERT INTO KHACHTHUE VALUES('KT0083','Le Thi Phuong Khanh','09/02/1999','273656107','BRVT')
INSERT INTO KHACHTHUE VALUES('KT0329','Nguyen Vinh Hai','03/01/1999','221421550','Phu Yen')
INSERT INTO KHACHTHUE VALUES('KT0137','Le Hoang Long','07/07/1999','184361699','Ha Tinh')

--XEMAY
INSERT INTO XEMAY VALUES ('X1942','Yamaha Exciter',150,80000 ,'Con')
INSERT INTO XEMAY VALUES ('X2719','Honda SH 150',153,100000,'Gan het')
INSERT INTO XEMAY VALUES ('X2739','Suzuki Raider',147,70000 ,'Het')
--E_BILL
INSERT INTO E_BILL VALUES (1,'01/11/2018','10/11/2018','KT0329')
INSERT INTO E_BILL VALUES (2,'07/12/2018','10/12/2018','KT0329')
INSERT INTO E_BILL VALUES (3,'18/12/2018','25/12/2018','KT0137')
--CTTHUE
INSERT INTO CTTHUE VALUES (1,'X2739',2)
INSERT INTO CTTHUE VALUES (1,'X2719',1)
INSERT INTO CTTHUE VALUES (2,'X2739',5)

--Cau 5--
SELECT X.MAXE, TenXe
FROM XeMay X, E_BILL E, CTTHUE C
WHERE C.MAXE = X.MAXE AND C.SOHD = E.SOHD
AND MONTH(NgThue) = 12	
AND YEAR(NgThue) = 2018
ORDER BY DUNGTICH


--Câu 6--

--c1:
SELECT TOP 1 WITH TIES MAXE, SUM(SL) SL_THUE 
FROM CTTHUE C, E_BILL E
WHERE C.SOHD = E.SOHD
AND YEAR(NgThue) = 2018
GROUP BY MAXE
ORDER BY SL_THUE DESC

--c2:
SELECT C.MAXE
FROM E_BILL E, CTTHUE C
WHERE E.SOHD = C.SOHD
AND YEAR(NgThue) = 2018
GROUP BY MAXE
HAVING SUM(SL) >= ALL (
SELECT SUM(SL)
FROM E_BILL E, CTTHUE C
WHERE E.SOHD = C.SOHD
AND YEAR(NgThue) = 2018
GROUP BY MAXE
)

GO
-- Câu 7 ---
SELECT K.MAKT, TENKT 
FROM KHACHTHUE K, XEMAY X, E_BILL E, CTTHUE C
WHERE K.MAKT = E.MAKT AND E.SOHD = C.SOHD AND X.MAXE = C.MAXE
AND DUNGTICH >= 100
EXCEPT 
SELECT K.MAKT, TENKT
FROM KHACHTHUE K, XEMAY X, E_BILL E, CTTHUE C
WHERE K.MAKT = E.MAKT AND E.SOHD = C.SOHD AND X.MAXE = C.MAXE
AND DUNGTICH < 100

--Câu 8--
SELECT MAKT, TENKT
FROM KHACHTHUE KT
WHERE YEAR(NGSINH) = 1999
AND NOT EXISTS	
	(SELECT *
	FROM XEMAY XM
	WHERE DUNGTICH >= 150 AND
	NOT EXISTS 
		(SELECT * FROM 
		E_BILL EB, CTTHUE CT
		WHERE KT.MAKT = EB.MAKT AND
		EB.SOHD = CT.SOHD 
		AND CT.MAXE = XM.MAXE
		)
	)