

--Cau 3--
ALTER TABLE CANHO
ADD CONSTRAINT CK_CH CHECK(
	(DIENTICH > 70 AND GIA > 2)
	OR DIENTICH <= 70
	)
	
--Cau 4--

--Bang rang buoc:
-------------------------------------
--|         THEM   |  XOA  |  SUA     |
--|CANHO  |   -    |  -(*) | + (GIA)  |
--|HOPDONG|   +    |   -   | +(DatCoc)|


CREATE TRIGGER TG_CH
ON CANHO 
FOR UPDATE
AS
BEGIN
	DECLARE @MACH VARCHAR(10), @GIA VARCHAR(10), @DATCOC VARCHAR(10)
	SELECT @MACH = MACH, @GIA = GIA FROM inserted
	SELECT @DATCOC = DATCOC FROM HOPDONG WHERE @MACH = MACH
	IF (@DATCOC >= 0.15*@GIA*1000)
	PRINT N'Cap Nhat Thanh Cong'
	ELSE
		BEGIN
			PRINT N'Loi Do...'
			ROLLBACK TRAN
		END
END

--Cau 5: --
SELECT C.MACH
FROM CANHO C, HOPDONG H
WHERE C.MACH = H.MACH 
AND MONTH(NgLap) BETWEEN 1 AND 3
YEAR(NgLap) = 2018
ORDER BY GIA DESC

--Cau 6---
--C1:
SELECT MACH
FROM HOPDONG H, CUTRU C
WHERE H.SOHD = C.SOHD
AND MONTH(NGKB) = 11 and YEAR(NGKB) = 2018
GROUP BY MACH
HAVING COUNT(CMND) >= ALL (
	SELECT COUNT(CMND) FROM CUTRU WHERE MONTH(NGKB) = 11 and YEAR(NGKB) = 2018
	GROUP BY MACH
)
--C2:
SELECT TOP 1 WITH TIES MACH
FROM HOPDONG H, CUTRU C
WHERE H.SOHD = C.SOHD
	AND MONTH(NGKB) = 11 
	AND YEAR(NGKB) = 2018
GROUP BY MACH 
ORDER BY COUNT(CMND) DESC


--8:---
SELECT CMND, HOTEN
FROM CUDAN CD
WHERE NOT EXISTS (
	SELECT * FROM CANHO CH
	WHERE GIA BETWEEN 2 AND 5
	AND NOT EXISTS (
		SELECT *
		FROM HOPDONG HD
		WHERE HD.CHUCH = CD.CMND AND 
		CH.MAKH = HD.MACH 
		AND YEAR(NGLAP) = 2018
		)
	)